services:
  redis:
    image: redis:latest
    container_name: demo-redis
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: demo-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: demo-kafka
    ports:
      - "9092:9092"
    environment:
      # Confluent KRaft (Zookeeper'sız) Mod Ayarları
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://localhost:9092,PLAINTEXT://demo-kafka:29092'
      KAFKA_LISTENERS: 'PLAINTEXT://demo-kafka:29092,CONTROLLER://demo-kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@demo-kafka:29093'
      CLUSTER_ID: 'demo-cluster-12345'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

  oracle:
    image: gvenzl/oracle-free:23-slim
    container_name: demo-oracle
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=oracle
      - APP_USER=openbanking
      - APP_PASSWORD=openbanking

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: demo-mssql
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Pass123

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: demo-redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: demo-kafka-ui
    ports:
      - "8089:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: demo-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: demo-kafka:29092
    depends_on:
      - kafka