# Configuration moved to application.yml
fixedDelayForApigwToken.in.milliseconds=5000

# spring.datasource.oracle.jdbc-url=jdbc:oracle:thin:@localhost:1521/FREE
# spring.datasource.oracle.username=openbanking
# spring.datasource.oracle.password=openbanking
# spring.datasource.oracle.driver-class-name=oracle.jdbc.OracleDriver

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=demoDB;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=YourStrong@Pass123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect