-- Legacy MySQL schema.
-- Note: Oracle and MSSQL schemas are now initialized programmatically in com.example.demo.config.DatabaseConfig
-- to support dual database configuration and handle database-specific SQL dialect differences.
